import "./globals.css";

import Header from "@/components/Header";
import Navbar from "@/components/Navbar";
import Notifications from "@/components/Notifications/Notifications";
import ReduxProvider from "@/components/ReduxProvider";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        {/* Wrap only client-side parts with ReduxProvider */}
        <ReduxProvider>
          <Header />
          <div className="flex h-screen overflow-auto">
            <Navbar />
            <main className="w-full">
              {children}
              <Notifications />
            </main>
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}