import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Header from "@/components/Header";
import Navbar from "@/components/Navbar";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className="flex h-screen overflow-auto">
          <div className="sticky top-0">
            <Navbar />
          </div>
          <main className="w-full">{children}</main>
        </div>
      </body>
    </html>
  );
}
