const authTypes = {
   LOGIN_REQUEST: 'LOGIN_REQUEST',
   LOGIN_SUCCESS: 'LOGIN_SUCCESS',
   LOGIN_FAILURE: 'LOGIN_FAILURE',

   REGISTER_REQUEST: 'REGISTER_REQUEST',
   REGISTER_SUCCESS: 'REGISTER_SUCCESS',
   REGISTER_FAILURE: 'REGISTER_FAILURE',

   VERIFY_OTP_REQUEST: 'VERIFY_OTP_REQUEST',
   VERIFY_OTP_SUCCESS: 'VERIFY_OTP_SUCCESS',
   VERIFY_OTP_FAILURE: 'VERIFY_OTP_FAILURE',

   CHANGE_PASSWORD_REQUEST: 'CHANGE_PASSWORD_REQUEST',
   CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
   CHANGE_PASSWORD_FAILURE: 'CHANGE_PASSWORD_FAILURE',

   LOGOUT: 'LOGOUT',
};

export default authTypes;
